# **En los siguientes ejercicios, no debes usar bucles o listas si no es absolutamente necesario (preferentemente metodos o recursos de Numpy)**

In [32]:
import numpy as np
import random as rd

##1.-Crea una matriz 3x4 con valores reales aleatorios entre 0 y 10

In [33]:
matriz_3x4 = np.random.rand(3,4)*10
matriz_3x4

array([[4.42157914, 3.63737528, 8.85173293, 2.68896606],
       [0.09883551, 3.39351684, 4.72470478, 7.56156765],
       [1.32200011, 7.91398718, 3.48076867, 4.38709525]])

##2.-De la matriz anterior haz un print de la primera fila y de la última. Luego imprime la primera columna y la última.

In [34]:
# Primera y última fila
print(matriz_3x4[0::2])

print()

# Primera y última columna
print(matriz_3x4[:, 0::3])

[[4.42157914 3.63737528 8.85173293 2.68896606]
 [1.32200011 7.91398718 3.48076867 4.38709525]]

[[4.42157914 2.68896606]
 [0.09883551 7.56156765]
 [1.32200011 4.38709525]]


##3.- Dada la matriz siguiente. Intercambia los elementos de las esquinas (2 a 2) de la matriz en el sentido de las diagonales. Es decir intercambia los elementos más extremos de la diagonal principal y luego los de la diagonal secundaria. Procura que el indexamiento que uses sea independiente de la matriz que utilicemos

In [35]:
matriz= np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9 ,10,11,12],
                 [13,14,15,16]])

len_matriz = len(matriz) - 1

print(f'Matriz original \n {matriz} \n')

#print(matriz[0, 0])
#print(matriz[0, -1])
#print(matriz[-1, 0])
#print(matriz[-1, -1])

matriz[0, 0], matriz[-1, -1] = matriz[-1, -1], matriz[0, 0]
matriz[0, -1], matriz[-1, 0] = matriz[-1, 0], matriz[0, -1]

print(f'Matriz final \n {matriz}')

Matriz original 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

Matriz final 
 [[16  2  3 13]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 4 14 15  1]]


##4.- Dada la matriz resultante del ejercicio anterior, muestra el shape de la misma, luego realiza un reshape para tener 4 matrices de 2x2 dentro de la misma. Vuelve a mostrar el nuevo shape

In [36]:
print(matriz.shape)
matriz = matriz.reshape(4, 2, 2)
print(matriz.shape)

(4, 4)
(4, 2, 2)


##5.- Obten un vector donde se le sume 10 a los elementos de la matriz original del ejercicio 3 que sean pares

In [37]:
matriz= np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9 ,10,11,12],
                 [13,14,15,16]])
vector = matriz[(matriz % 2 == 0)] + 10
vector

array([12, 14, 16, 18, 20, 22, 24, 26])

##6.- Crea dos matrices cuadradas de las dimensiones que tu quieras, con valores aleatorios y sumalas

In [38]:
m1 = np.random.randint(0, 100, (4, 4))
m2 = np.random.randint(0, 100, (4, 4))
print(f'{m1} \n')
print(f'{m2} \n')
print(m1 + m2)

[[ 9 32 68 34]
 [71 72 84 62]
 [18 69 79 24]
 [65 49  1 56]] 

[[49 48 57 79]
 [67 11 90 15]
 [36 99 18 55]
 [40 29 41 91]] 

[[ 58  80 125 113]
 [138  83 174  77]
 [ 54 168  97  79]
 [105  78  42 147]]


##7.- Con la matriz original del ejercicio 3 crea una matriz 3x3 que excluya a la primera fila y la primera columna. Hazlo de la forma más breve que puedas (usando indexado). Tu método debe ser aplicable a cualquier matriz de tamaño nxn para obtener una matriz (n-1)x(n-1)

In [39]:
matriz_3x3 = matriz[1:, 1:]
print(matriz_3x3)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


##8.- Crea un vector de tamaño 10 con valores reales equiespaciados entre 100.0 y 245.0

In [40]:
vector2=np.linspace(100.0,245.0,10)
print(vector2)

[100.         116.11111111 132.22222222 148.33333333 164.44444444
 180.55555556 196.66666667 212.77777778 228.88888889 245.        ]


##9.- Reescala el vector anterior para que sus valores queden entre 0 y 1

In [41]:
vectorEscalado=vector2/vector2.max()
vectorEscalado

array([0.40816327, 0.4739229 , 0.53968254, 0.60544218, 0.67120181,
       0.73696145, 0.80272109, 0.86848073, 0.93424036, 1.        ])

##10.- Intenta reescalar el vector del ejercicio 8 para que sus valores esten entre -1 y 1

In [42]:
print(np.median(vector2))
vectorEscalado_1=(vector2-np.median(vector2))
vectorEscalado_1/=vectorEscalado_1.max()
vectorEscalado_1

172.5


array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])