##**La libreria Numpy. Manejo de arrays y matrices orientado a modelos de IA**



In [2]:
import numpy as np
import random as rd  #Generalmente no es necesaria, numpy tiene sus propias metodos aleatorios

##Formas habituales de definir e inicializar vectores y matrices Numpy

In [ ]:
#Desde una lista definida a mano
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# En este caso una creada por comprensión
arr=np.array([i for i in range(1,6)])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#Pero no es necesario crear la lista tenemos el metodo arange
arr=np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [ ]:
#Si queremos crear una serie de numeros en punto flotante (equiespaciados)
arr=np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#Crear con Numpy una matriz bidimensional sin inicializar de 4x8
matriz = np.empty((4,8))
print('Sin inicializar:',matriz)

#Crear una matriz 4x4 de enteros a ceros
matrix = np.zeros((4,4),dtype=np.int64)
print('Matriz con ceros',matrix)

#Lo mismo de antes pero rellena con numeros enteros aleatorios
matriz = np.random.randint(0,100,(4,8))
print('Con numeros enteros aleatorios:',matriz)

#Ahora con numeros en punto flotante
matriz = np.random.rand(4,8)
print('Aleatoria con numeros p. flotante',matriz)

#Ahora con numeros aleatorios siguiendo una distribucion uniforme entre -10 y 10
matriz = np.random.uniform(-10,10,(4,8))
print('Distribucion uniforme entre -10 y 10',matriz)

#Ahora con una distribucion normal
matriz = np.random.normal(0,1,(4,8))
print('Distribucion normal:',matriz)

#Ahora con una distribucion chi cuadrado
matriz = np.random.chisquare(5,(4,8))
print('Distribucion chi cuadrado:',matriz)

Sin inicializar: [[ 0.90913149  3.9604836   2.87078384  5.45717088  8.96203266  3.24059884
   9.96683456  3.82532187]
 [ 5.12240073  3.82062638  5.08217583  4.73831074  5.93311008  6.6481246
  10.08890249  6.95123995]
 [ 5.98601921  2.99799132  2.11618757  2.51963506  2.73867624  6.68050643
   1.78680624  2.56631066]
 [ 8.62453162  4.13576416  6.42362617 10.14245881  5.00008347  7.19194031
   2.21846547 11.54231196]]
Matriz con ceros [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Con numeros enteros aleatorios: [[89 80 80 20 40 48 56 47]
 [96 93 17 97 94 86 40 10]
 [65 98 33 60 10 11 71 74]
 [11 54 72 58 46 77 17 18]]
Aleatoria con numeros p. flotante [[0.88612435 0.01490611 0.36294174 0.67930849 0.06127464 0.90592886
  0.34222369 0.18948858]
 [0.00669666 0.66882307 0.37543719 0.8935643  0.86468237 0.38674158
  0.624604   0.99030999]
 [0.99379772 0.75560881 0.40550351 0.23838828 0.97958461 0.80144381
  0.94163985 0.39378723]
 [0.51465455 0.69953586 0.8811688  0.33072256 0.57581117 0.9294

##Gestión de tipos en Numpy

In [ ]:
#Crear una matrix 10x4x4 con numeros int64
arr = np.random.randint(0,100,(2,4,4))
print(arr.dtype)
print(arr)

#Convertir la matriz anterior a float32
arr = arr.astype(np.float32)
print(arr.dtype)
print(arr)

#Convertir la matriz anterior a float64
arr = arr.astype(np.float64)
print(arr.dtype)
print(arr)

int64
[[[ 3 42 81 28]
  [ 0 79 45  5]
  [29 81 81 64]
  [ 6 79 62 41]]

 [[22 71 92 93]
  [32  0 24  0]
  [33  5 20 69]
  [11  7  6 61]]]
float32
[[[ 3. 42. 81. 28.]
  [ 0. 79. 45.  5.]
  [29. 81. 81. 64.]
  [ 6. 79. 62. 41.]]

 [[22. 71. 92. 93.]
  [32.  0. 24.  0.]
  [33.  5. 20. 69.]
  [11.  7.  6. 61.]]]
float64
[[[ 3. 42. 81. 28.]
  [ 0. 79. 45.  5.]
  [29. 81. 81. 64.]
  [ 6. 79. 62. 41.]]

 [[22. 71. 92. 93.]
  [32.  0. 24.  0.]
  [33.  5. 20. 69.]
  [11.  7.  6. 61.]]]


##Indexado sobre arrays y matrices numpy

In [ ]:
#Manejo de indices en numpy
arr = np.arange(1,10)
print(arr)
print(arr[0])
print(arr[1])
print(arr[::2])
print(arr[-1])
print(arr[-1::-2])

[1 2 3 4 5 6 7 8 9]
1
2
[1 3 5 7 9]
9
[9 7 5 3 1]


In [ ]:
#Ahora con una matriz 4x4
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]
                  ])
print(matrix)

print(matrix[0,3])
print(matrix[0,1:3:])
print(matrix[1,::-1])
print(matrix[::-1,0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
4
[2 3]
[8 7 6 5]
[13  9  5  1]


In [ ]:
#Extraer las filas pares de matrix
print(matrix)
print(matrix[::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
#invertir el orden de las filas de matrix
print(matrix)
print()
print(matrix[::-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
#invertir el orden de las columnas de la matriz matrix
print(matrix)
print()
print(matrix[:,::-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
#Obtener la traspuesta de matrix
print(matrix)
print()
print(matrix.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [ ]:
#La traspuesta pero con un bucle
print(matrix)
matrizT=np.zeros((matrix.shape[1],matrix.shape[0]),dtype=np.int64)
for i in range(matrizT.shape[0]):
    matrizT[i]=matrix[:,i]
print('Traspuesta')
print(matrizT)

[[22 37 41 13]
 [75 98 73 77]
 [41 30 81 54]
 [57 81 67 84]]
Traspuesta
[[22 75 41 57]
 [37 98 30 81]
 [41 73 81 67]
 [13 77 54 84]]


In [5]:
#Intercambiar 2 columnas
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]
                  ])
matrix[:,[1,2]]=matrix[:,[2,1]]
print(matrix)

[[ 1  3  2  4]
 [ 5  7  6  8]
 [ 9 11 10 12]
 [13 15 14 16]]


In [6]:
#Intercambiar las filas 0 y 2 de matrix
print(matrix)
print()
#matrix[0]=matrix[2]
matrix[[0,2]]=matrix[[2,0]]
print(matrix)

[[ 1  3  2  4]
 [ 5  7  6  8]
 [ 9 11 10 12]
 [13 15 14 16]]

[[ 9 11 10 12]
 [ 5  7  6  8]
 [ 1  3  2  4]
 [13 15 14 16]]


In [ ]:
a=1
b=2
a,b=b,a
print(a,b)

2 1


##Cambiando la forma de los vectores y matrices

In [ ]:
arr=np.arange(9)
print(arr)
print(arr.shape)
matrix=arr.reshape(3,3)
print(matrix)
print(matrix.shape)

[0 1 2 3 4 5 6 7 8]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [ ]:
#Ejemplo partiendo de una matriz 4x4 a 4x2x2
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]
                  ])
matrix.reshape(4,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [ ]:
#aplanar la matriz
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix)
print(matrix.flatten())
print(np.ravel(matrix))  #otras formas
print(matrix.reshape(-1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


##Aplicando operaciones a los vectores y matrices numpy

In [ ]:
#sumar un numero a todo un vector
arr=np.arange(10)
print(arr)
print(arr+10)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
#multiplicar dos vectores numpy
arr1=np.arange(10)
arr2=np.arange(100,110)
print(arr1)
print(arr2)
print(arr1*arr2)

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]
[  0 101 204 309 416 525 636 749 864 981]


In [ ]:
#Dividir una matriz numpy por el mayor de sus valores
matrix=np.random.randint(0,100,(4,4))
print(matrix)
max=matrix.max()
print(max)
print(matrix/max)
print(matrix.dtype)
#Esto resulta en la normalización de la matriz a valores entre 0 y 1

[[55 38 61 68]
 [44 54 73 27]
 [23 63 61 22]
 [89 43 26 63]]
89
[[0.61797753 0.42696629 0.68539326 0.76404494]
 [0.49438202 0.60674157 0.82022472 0.30337079]
 [0.25842697 0.70786517 0.68539326 0.24719101]
 [1.         0.48314607 0.29213483 0.70786517]]
int64


In [ ]:
#La media de los valores de una matriz o un vector
print(matrix.mean())

50.625


In [ ]:
#La desviación típica de una matriz o un vector
matrix.std()

np.float64(19.098020185349057)

In [ ]:
#La suma de los valores de una matriz o un vector
matrix.sum()

np.int64(592)

In [ ]:
#aplicar una funcion a vectores numpy
def cuadrado_de_la_diferencia(a,b):
    return (a-b)**2

vectorA=np.array([2,3,4,5,6,7])
vectorB=np.array([1,2,3,4,5,6])
print(cuadrado_de_la_diferencia(vectorA,vectorB))


[1 1 1 1 1 1]


In [ ]:
# multiplicar 2 matrices 3x3 producto elemento a elemento
matrizA=np.array([[1,2,3]
                 ,[4,5,6]
                 ,[7,8,9]])
matrizB=np.array([[1,2,3]
                 ,[4,5,6]
                 ,[7,8,9]])
print(matrizA*matrizB)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
#hacemos el producto matricial entre matrizA y matrizB
matrizA.dot(matrizB)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
#Añadir a una matriz 3x3 una fila
matriz=np.array([[1,2,3]
                 ,[4,5,6]
                 ,[7,8,9]])
fila=np.array([10,11,12])
print(matriz)
print(np.vstack((matriz,fila)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Añadir una columna a una matriz 3x3
matriz=np.array([[1,2,3]
                 ,[4,5,6]
                 ,[7,8,9]])
columna=np.array([10,11,12])
print(matriz)
print(np.hstack((matriz,columna.reshape(3,1))))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [ ]:
#Insertar una columna en una matriz en la posicion 1
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

columna = np.array([[10, 11, 12],[13,14,15]])
matriz2 = np.insert(matriz, 0, columna, axis=1)
print(matriz2)

[[10 13  1  2  3]
 [11 14  4  5  6]
 [12 15  7  8  9]]


In [ ]:
#Insertar una fila en una matriz en la posicion 1
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

fila = np.array([10, 11, 12])
matriz2 = np.insert(matriz, 1, fila, axis=0)
print(matriz2)

[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#calcular el determinante de una matriz
print(matrix)
print(np.linalg.det(matrix))

[[1 2 3]
 [4 5 6]
 [7 3 9]]
-29.99999999999999


In [ ]:
#calcular la inversa de una matriz
matrix=np.array([[1,2,3]
                 ,[4,5,6]
                 ,[7,3,9]])
print(matrix)
inv=np.linalg.inv(matrix)
print(inv)
print(np.round(inv.dot(matrix)))

[[1 2 3]
 [4 5 6]
 [7 3 9]]
[[-0.9         0.3         0.1       ]
 [-0.2         0.4        -0.2       ]
 [ 0.76666667 -0.36666667  0.1       ]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


##Operaciones de seleccion de elementos y argmax

In [ ]:
#De un vector numpy seleccionar los elementos entre 10 y 50 no incluidos
ar=np.random.randint(1,100,10)
print(ar)
print(ar[(ar>10) & (ar<50)])

[57 23 57 14 47 18 26 47 63 14]
[23 14 47 18 26 47 14]


In [ ]:
#Extraemos la primera columna de la matriz y seleccionamos los pares
matrix=np.array([[1,2,3]
                ,[4,5,6]
                ,[7,3,9]])

columna=matrix[:,0]
columna[(columna%2!=0)]

array([1, 7])

In [ ]:
#uso del metodo argmax
matrix=np.array([[1,2,3]
                ,[4,5,6]
                ,[7,3,9]])
print(np.argmax(matrix,axis=0))
print(np.argmax(matrix,axis=1))

[2 1 2]
[2 2 2]


In [ ]:
#Ejemplo codificación onehot encoder y reversa

def onehot(entero,tam):
    vector=np.zeros(tam,dtype=np.int64)
    vector[entero]=1
    return vector

def reverse_onehot(vector):
    return np.argmax(vector,axis=len(vector.shape)-1)

arr=np.random.randint(0,9,(10))
print(arr)
arrhot=np.array([onehot(arr[i],10) for i in range(arr.size)])
print(arrhot)
print(reverse_onehot(arrhot))

[7 1 2 0 2 6 0 8 5 4]
[[0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]
[7 1 2 0 2 6 0 8 5 4]


In [ ]:
vector = np.array([0, 1, 0])
vector_de_vectores = np.array([[0, 0, 1],
                           [1, 0, 0],
                           [0, 1, 0],
                            [0, 0, 1],
                           [1, 0, 0],
                           [0, 1, 0]])


print(reverse_onehot(vector))
print()
print(reverse_onehot(vector_de_vectores))