# PRUEBAS CON NUMPY

In [ ]:
import numpy as np

In [ ]:
# Invertir el orden de las columnas
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(matriz)
print()
print(matriz[:, ::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
