# **En los siguientes ejercicios, no debes usar bucles o listas si no es absolutamente necesario (preferentemente metodos o recursos de Numpy)**

In [56]:
import numpy as np

##1.-Crea una matriz 3x4 con valores reales aleatorios entre 0 y 10

In [58]:
matriz3x4=np.random.rand(3,4)*10  #Una forma
print(matriz3x4)
matriz3x4 = np.random.uniform(0, 10, size=(3,4)) #Otra forma
matriz3x4

[[7.36029586 1.610054   5.65195817 2.31257546]
 [7.00653333 1.26842799 8.57994733 1.31030652]
 [5.6511678  4.7354781  6.71257019 5.61220777]]


array([[8.15847712, 5.41060204, 4.93819383, 3.38465122],
       [8.15380395, 4.72070958, 6.49165187, 9.97990721],
       [5.6902856 , 8.29564223, 8.07343518, 6.27538267]])

##2.-De la matriz anterior haz un print de la primera fila y de la última. Luego imprime la primera columna y la última.

In [59]:
print(matriz3x4[0,:])
print(matriz3x4[-1,:])
print(matriz3x4[:,0])
print(matriz3x4[:,-1])

[8.15847712 5.41060204 4.93819383 3.38465122]
[5.6902856  8.29564223 8.07343518 6.27538267]
[8.15847712 8.15380395 5.6902856 ]
[3.38465122 9.97990721 6.27538267]


##3.- Dada la matriz siguiente. Intercambia los elementos de las esquinas (2 a 2) de la matriz en el sentido de las diagonales. Es decir intercambia los elementos más extremos de la diagonal principal y luego los de la diagonal secundaria. Procura que el indexamiento que uses sea independiente de la matriz que utilicemos

In [60]:
matriz= np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9 ,10,11,12],
                 [13,14,15,16]])
matriz[0,0],matriz[-1,-1]=matriz[-1,-1],matriz[0,0]
matriz[0,-1],matriz[-1,0]=matriz[-1,0],matriz[0,-1]
print(matriz)


[[16  2  3 13]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 4 14 15  1]]


##4.- Dada la matriz resultante del ejercicio anterior, muestra el shape de la misma, luego realiza un reshape para tener 4 matrices de 2x2 dentro de la misma. Muestra la nueva matriz

In [ ]:
print(matriz.shape)
nueva=matriz.reshape(4,2,2)
print(nueva)

(4, 4)
[[[16  2]
  [ 3 13]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[ 4 14]
  [15  1]]]


##5.- Obten un vector donde se le sume 10 a los elementos de la matriz original del ejercicio 3 que sean pares

In [ ]:
matriz= np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9 ,10,11,12],
                 [13,14,15,16]])
matriz[(matriz%2==0)]+10

array([12, 14, 16, 18, 20, 22, 24, 26])

##6.- Crea dos matrices cuadradas de las dimensiones que tu quieras, con valores aleatorios y sumalas

In [ ]:
matriz1= np.random.randint(0,100,(4,4))
print(matriz1)
matriz2= np.random.randint(0,100,(4,4))
print(matriz2)
print(matriz1+matriz2)

[[56 24 16 19]
 [32 99 86 13]
 [37 49 11 41]
 [53 36 27 19]]
[[46 32 72 38]
 [78 33 70 17]
 [99 22 58 61]
 [75 81 82 58]]
[[102  56  88  57]
 [110 132 156  30]
 [136  71  69 102]
 [128 117 109  77]]


##7.- Con la matriz original del ejercicio 3 crea una matriz 3x3 que excluya a la primera fila y la primera columna. Hazlo de la forma más breve que puedas (usando indexado). Tu método debe ser aplicable a cualquier matriz de tamaño nxn para obtener una matriz (n-1)x(n-1)

In [ ]:
matriz= np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9 ,10,11,12],
                 [13,14,15,16]])
matriz_peque=matriz[1:,1:]
print(matriz_peque)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


##8.- Crea un vector de tamaño 10 con valores reales equiespaciados entre 100.0 y 245.0

In [ ]:
vectorillo=np.linspace(100.0,245.0,10)
print(vectorillo)

[100.         116.11111111 132.22222222 148.33333333 164.44444444
 180.55555556 196.66666667 212.77777778 228.88888889 245.        ]


##9.- Reescala el vector anterior para que sus valores queden entre 0 y 1

In [ ]:
vectorEscalado=vectorillo/vectorillo.max()
vectorEscalado

array([0.40816327, 0.4739229 , 0.53968254, 0.60544218, 0.67120181,
       0.73696145, 0.80272109, 0.86848073, 0.93424036, 1.        ])

##10.- Intenta reescalar el vector del ejercicio 8 para que sus valores esten entre -1 y 1

In [ ]:
print(np.median(vectorillo))
vectorEscalado_1=(vectorillo-np.median(vectorillo))
vectorEscalado_1/=vectorEscalado_1.max()
vectorEscalado_1

172.5


array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])